on: [push, release]
name: Build
jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "gradle"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install rpm-tools on Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
            sudo apt-get update
            sudo apt-get install rpm

      - name: Build linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          ./gradlew --no-daemon appAndroid:build
          ./gradlew --no-daemon package

      - name: Build Windows
        if: matrix.os == 'windows-latest'
        run: |
          ./gradlew --no-daemon :appDesktop:createDistributable
          cd appDesktop/build/compose/binaries/main/
          Compress-Archive -Path app -Destination genesis.zip

      - name: Build iOS Release
        if: matrix.os == 'macos-latest' && startsWith(github.ref, 'refs/tags/')
        run: |
          xcrun xcodebuild archive -project appiOS/genesis.xcodeproj -scheme genesis -configuration Release -archivePath "appIos/build/genesis.xcarchive" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
          cd appIos/build/genesis.xcarchive/Products
          mv Applications Payload
          zip -r ../../genesis.ipa Payload

      - name: Build iOS Debug
        if: matrix.os == 'macos-latest' && !startsWith(github.ref, 'refs/tags/')
        run: |
          xcrun xcodebuild archive -project appiOS/genesis.xcodeproj -scheme genesis -configuration Debug -archivePath "appIos/build/genesis.xcarchive" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
          cd appIos/build/genesis.xcarchive/Products
          mv Applications Payload
          zip -r ../../genesis.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v3
        if: matrix.os == 'macos-latest'
        with:
          name: genesis.ipa
          path: appIos/build/genesis.ipa

      - name: Upload DEB
        uses: actions/upload-artifact@v3
        if: matrix.os == 'ubuntu-latest'
        with:
          name: genesis.deb
          path: appDesktop/build/compose/binaries/main/deb/*.deb

      - name: Upload RPM
        uses: actions/upload-artifact@v3
        if: matrix.os == 'ubuntu-latest'
        with:
          name: genesis.rpm
          path: appDesktop/build/compose/binaries/main/rpm/*.rpm

      - name: Upload ZIP
        uses: actions/upload-artifact@v3
        if: matrix.os == 'windows-latest'
        with:
          name: genesis.zip
          path: appDesktop/build/compose/binaries/main/genesis.zip

      - name: Upload EXE
        uses: actions/upload-artifact@v3
        if: matrix.os == 'windows-latest'
        with:
          name: genesis.exe
          path: appDesktop/build/compose/binaries/main/exe/*.exe

      - name: Upload Release APK
        uses: actions/upload-artifact@v3
        if: matrix.os == 'ubuntu-latest' && startsWith(github.ref, 'refs/tags/')
        with:
          name: genesis.apk
          path: appAndroid/build/outputs/apk/release/appAndroid-release-unsigned.apk

      - name: Upload Debug APK
        uses: actions/upload-artifact@v3
        if: matrix.os == 'ubuntu-latest' && !startsWith(github.ref, 'refs/tags/')
        with:
          name: genesis.apk
          path: appAndroid/build/outputs/apk/debug/appAndroid-debug.apk

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            appDesktop/build/compose/binaries/main/deb/*.deb
            appDesktop/build/compose/binaries/main/genesis.zip
            appAndroid/build/outputs/apk/release/appAndroid-release-unsigned.apk
            appIos/build/genesis.ipa
