on: [push, release]
name: Build
jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "gradle"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build
        run: |
          ./gradlew --no-daemon build
          ./gradlew --no-daemon package

      - name: Build iOS Release
        if: matrix.os == 'macos-latest' && github.event_name == 'release'
        run: |
          cd appiOS
          xcrun xcodebuild build
          xcrun /usr/bin/xcodebuild -scheme iosApp -configuration Release clean archive -archivePath "build/genesis.xcarchive" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
          cd build/genesis.xcarchive/Products/Applications/Genesis.app
          zip -r ../../../../genesis.ipa .

      - name: Build iOS
        if: matrix.os == 'macos-latest' && github.event_name == 'push'
        run: |
          cd appiOS
          xcrun xcodebuild build
          xcrun /usr/bin/xcodebuild -scheme iosApp -configuration Debug clean archive -archivePath "build/genesis.xcarchive" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
          cd build/genesis.xcarchive/Products/Applications/Genesis.app
          zip -r ../../../../genesis.ipa .

      - name: debug
        run: |
          ls /appDesktop/build/compose/binaries/main

      # - name: Upload EXE
      #   uses: actions/upload-artifact@v3
      #   if: matrix.os == 'windows-latest'
      #   with:
      #     name: genesis.exe
      #     path: appDesktop/build/

      - name: Upload DMG
        uses: actions/upload-artifact@v3
        if: matrix.os == 'macos-latest'
        with:
          path: appDesktop/build/compose/binaries/main/dmg/*.dmg

      - name: Upload APK
        uses: actions/upload-artifact@v3
        if: matrix.os == 'ubuntu-latest' && github.event_name == 'push'
        with:
          name: genesis.apk
          path: appAndroid/build/outputs/apk/debug/appAndroid-debug.apk

      - name: Upload APK
        uses: actions/upload-artifact@v3
        if: matrix.os == 'ubuntu-latest' && github.event_name == 'release'
        with:
          name: genesis.apk
          path: appAndroid/build/outputs/apk/release/appAndroid-release-unsigned.apk

      - name: Upload IPA
        uses: actions/upload-artifact@v3
        if: matrix.os == 'macos-latest'
        with:
          name: genesis.ipa
          path: appIos/build/genesis.ipa
