on:
  push:
    paths:
      - .github/workflows/publish.yml
      - genesis/discord/**
      - genesis/genesisApi/**
  release:
    types: [ created ]
name: Publish
jobs:
  publish:
    name: Publish
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "gradle"

      - name: Cache genesisDiscordApi
        uses: actions/cache@v3
        with:
          path: genesis/discord/api/build
          key: ${{ runner.os }}-genesis-discord-api-${{ hashFiles('genesis/discord/api/**', 'build.gradle.kts', 'gradle.properties', 'gradle/libs.versions.toml') }}
      - name: Cache genesisDiscordClient
        uses: actions/cache@v3
        with:
          path: genesis/discord/client/build
          key: ${{ runner.os }}-genesis-discord-client-${{ hashFiles('genesis/discord/client/**', 'build.gradle.kts', 'gradle.properties', 'gradle/libs.versions.toml') }}
      - name: Cache genesisApi
        uses: actions/cache@v3
        with:
          path: genesis/genesisApi/build
          key: ${{ runner.os }}-genesis-genesisApi-${{ hashFiles('genesis/genesisApi/**', 'build.gradle.kts', 'gradle.properties', 'gradle/libs.versions.toml') }}

      - name: Publish
        run: |
          ./gradlew --no-daemon publish
        env:
          REPOSILITE_PASSWORD: ${{ secrets.REPOSILITE_PASSWORD }}